# Generated by Django 5.1.1 on 2024-09-15 18:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('air_quality_index', models.FloatField()),
                ('pollution_level', models.FloatField()),
                ('human_activity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('habitat', models.TextField()),
                ('photo', models.ImageField(upload_to='species_photos/')),
                ('last_sighted', models.DateTimeField(auto_now=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('alert_type', models.CharField(max_length=100)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redlistapp.species')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='report_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='report_videos/')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('environmental_conditions', models.JSONField(default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redlistapp.species')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redlistapp.userprofile')),
            ],
        ),
    ]
