# Generated by Django 5.1.1 on 2024-09-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlistapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='photo',
            field=models.ImageField(max_length=200, upload_to='species_photos/'),
        ),
    ]
